FROM python:3.12-slim-bullseye  # Or a suitable base image

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libz-dev \
    zlib1g-dev

# Copy requirements and install Python packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your app code
COPY . .

# Set the Streamlit port
EXPOSE 8501

# Run Streamlit
CMD ["streamlit", "run", "dashboardgen.py"]